name = "psyblr-server"
main = "src/index.ts"
compatibility_date = "2026-05-18"

[[durable_objects.bindings]]
name = "PSYBLR_ROOM"
class_name = "PsyblrRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["PsyblrRoom"]
